name: inception

services:
  nginx:
    build:
      context: requirements/nginx
    expose:
      - "443"
    ports:
      - "443:443"
    restart: always
    container_name: nginx
    depends_on:
      mariadb:
        condition: service_healthy
      wordpress:
        condition: service_healthy
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    volumes:
      - wordpress_files:/mnt/wordpress
    networks:
      - inception

  wordpress:
    build:
      context: requirements/wordpress
    expose:
      - "9000"
    restart: always
    container_name: wordpress
    env_file:
      - path: .env
    environment:
      - CREDENTIALS_FILE=/run/secrets/wp_credentials
      - DB_PASSWD_FILE=/run/secrets/db_password
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "ps aux | grep 'php-fpm: master process'"]
      interval: 10s
      retries: 2
    configs:
      - source: php_fpm_config
        target: /etc/php/7.4/fpm/pool.d/wordpress.conf
    volumes:
      - wordpress_files:/mnt/wordpress
    secrets:
      - db_password
      - wp_credentials
    networks:
      - inception

  mariadb:
    build:
      context: requirements/mariadb
    expose:
      - "3306"
    restart: always
    container_name: mariadb
    env_file:
      - path: .env
    environment:
      - DB_PASSWD_FILE=/run/secrets/db_password
      - DB_ROOT_PASSWD_FILE=/run/secrets/db_root_password
    healthcheck:
      test: ["CMD", "mariadb-admin", "-u=root", "ping"]
      interval: 10s
      retries: 2
    configs:
      - source: mariadbd_config
        target: /etc/mysql/mariadb.conf.d/myconfig.cnf
    volumes:
      - Db:/mnt/db
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception

  adminer:
    build:
      context: requirements/bonus/adminer
    ports:
      - "8080:8080"
    restart: on-failure
    container_name: adminer
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception

  mailhog:
    build:
      context: requirements/bonus/mailhog
    restart: on-failure
    container_name: mailhog
    expose:
      - "8025"
      - "1025"
    ports:
      - "6123:8025"
    networks:
      - inception
  
  ftp:
    build:
      context: requirements/bonus/ftp
    restart: on-failure
    container_name: ftp
    expose:
      - "21"
    ports:
      - "21:21"
      - "30000-30010:30000-30010"
    volumes:
      - wordpress_files:/mnt/wordpress

  redis:
    build:
      context: requirements/bonus/redis
    restart: on-failure
    container_name: redis
    networks:
      - inception

  static_site:
    build:
      context: requirements/bonus/quote
    restart: on-failure
    container_name: static_site
    expose:
      - "80"
    ports:
      - "8081:80"
    configs:
      - source: bonus_nginx_config
        target: /etc/nginx/nginx.conf

configs:
  nginx_config:
    file: requirements/nginx/conf/nginx.conf
  php_fpm_config:
    file: requirements/wordpress/conf/wordpress.conf
  mariadbd_config:
    file: requirements/mariadb/conf/myconfig.cnf
  bonus_nginx_config:
    file: requirements/bonus/quote/conf/nginx.conf

secrets:
  db_password:
    file: /home/alafdili/inception/secrets/db_password.txt
  db_root_password:
    file: /home/alafdili/inception/secrets/db_root_password.txt
  wp_credentials:
    file: /home/alafdili/inception/secrets/credentials.txt

volumes:
  wordpress_files:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/alafdili/data/Wordpress
  Db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/alafdili/data/DB

networks:
  inception:
    driver: bridge